In [1]:
import pandas as pd

In [3]:
data = [1,2,3,4,5]
series = pd.Series(data)

print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

1d data obj to hold any data type

In [4]:
data = {'a':1, 'b':2, 'c':3}

series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

┌───────────────────────┬──────────────────┬────────────────────────┐ 
 │ Use case              │ pandas Series    │ NumPy array            │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Data wrangling /      │ ✅ Excel-style:  │ ⚠️ Possible but you    │ 
 │ analysis              │ CSV columns,     │ hand-roll              │ 
 │                       │ .groupby,        │ labels/filtering       │ 
 │                       │ pivots, category │                        │ 
 │                       │ counts, rolling  │                        │ 
 │                       │ stats            │                        │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Labeled/time-series   │ ✅ Weather by    │ ❌ Labels not native   │ 
 │ data                  │ date, stock      │                        │ 
 │                       │ prices by        │                        │ 
 │                       │ ticker, survey   │                        │ 
 │                       │ responses        │                        │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Mixing data from a    │ ✅ Mixed object  │ ⚠️ Becomes object      │ 
 │ file                  │ column, NaN gaps │ array, slower, clunky  │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Machine-learning      │ ⚠️ One column;   │ ✅ Standard for model  │ 
 │ pipelines             │ usually you then │ training loops,        │ 
 │                       │ convert to       │ mini-batches,          │ 
 │                       │ array/X matrix   │ GPU/sklearn interop    │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Linear algebra /      │ ⚠️ Not for this  │ ✅ Dot products,       │ 
 │ physics / math        │                  │ matmul, broadcasting,  │ 
 │                       │                  │ (M,N) grids            │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Image processing /    │ ❌               │ ✅ Pixels = (H,W,3)    │ 
 │ signals               │                  │ arrays, FFT,           │ 
 │                       │                  │ convolution kernels    │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Large-scale number    │ ⚠️ Slower for    │ ✅ Contiguous memory,  │ 
 │ crunching             │ big unlabeled    │ vectorized C           │ 
 │                       │ math             │ operations             │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ Web/API JSON output   │ ⚠️ .tolist()     │ ✅                     │ 
 │                       │ first            │ .tolist()/.tobytes()   │ 
 │                       │                  │ easy, JSON-friendly    │ 
 ├───────────────────────┼──────────────────┼────────────────────────┤ 
 │ You need              │ ✅               │ ❌ Build a dict or     │ 
 │ .loc["name"],         │                  │ index math yourself    │ 
 │ .between(), .dt.day   │                  │                        │ 
 └───────────────────────┴──────────────────┴───────────────────────

In [8]:
##Dataframe 
## multiple rows and coloumns
##create df from dict of list

data={
    'Name':['Ahad', 'Suha', 'Jack', 'John'],
    'Age':[25,30,45,55],
    'City':['QAT','NY','BLR','TX']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

   Name  Age City
0  Ahad   25  QAT
1  Suha   30   NY
2  Jack   45  BLR
3  John   55   TX
<class 'pandas.DataFrame'>

In [11]:
##list of dict

data=[
     {'Name':'Ahad', 'Age':32, 'City':'QAt'},
     {'Name':'Suha', 'Age':32, 'City':'QAt'},     
     {'Name':'E', 'Age':32, 'City':'QAt'},
]
df = pd.DataFrame(data)
print(df)

   Name  Age City
0  Ahad   32  QAt
1  Suha   32  QAt
2     E   32  QAt

In [19]:
df = pd.read_csv('../data/sales_data_sample.csv', encoding='cp1251')

df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [20]:
## accessing the data from each frame
df['STATUS']

0        Shipped
1        Shipped
2        Shipped
3        Shipped
4        Shipped
          ...
2818     Shipped
2819     Shipped
2820    Resolved
2821     Shipped
2822     On Hold
Name: STATUS, Length: 2823, dtype: str

In [31]:
df.loc[1]

ORDERNUMBER                      10121
QUANTITYORDERED                     34
PRICEEACH                        81.35
ORDERLINENUMBER                      5
SALES                           2765.9
ORDERDATE                5/7/2003 0:00
STATUS                         Shipped
QTR_ID                               2
MONTH_ID                             5
YEAR_ID                           2003
PRODUCTLINE                Motorcycles
MSRP                                95
PRODUCTCODE                   S10_1678
CUSTOMERNAME        Reims Collectables
PHONE                       26.47.1555
ADDRESSLINE1        59 rue de l'Abbaye
ADDRESSLINE2                       NaN
CITY                             Reims
STATE                              NaN
POSTALCODE                       51100
COUNTRY                         France
TERRITORY                         EMEA
CONTACTLASTNAME                Henriot
CONTACTFIRSTNAME                  Paul
DEALSIZE                         Small
Name: 1, dtype: object

In [35]:
### accessiong a specified element
df.at[1,'SALES']

np.float64(2765.9)

In [37]:
df.drop('SALES', axis=1,)
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [38]:
df['SALES']=df['SALES']+1
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2872.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2766.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3885.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3747.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5206.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2245.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3979.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5418.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2117.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3080.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [39]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3554.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,483.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2204.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3185.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4509.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14083.800000,4.000000,12.000000,2005.00000,214.000000